Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,42 +4,42 @@ jobs:
     docker:
       # using custom image, see .circleci/images/primary/Dockerfile
       - image: circleci/python
-      - image: postgres:9.4.1
-        environment:
-          POSTGRES_USER: ubuntu
-          POSTGRES_DB: contacts
-    working_directory: /go/src/github.com/circleci/cci-demo-docker
+#       - image: postgres:9.4.1
+#         environment:
+#           POSTGRES_USER: ubuntu
+#           POSTGRES_DB: contacts
+#     working_directory: /go/src/github.com/circleci/cci-demo-docker
 
-    environment:
-      TEST_RESULTS: /tmp/test-results
+#     environment:
+#       TEST_RESULTS: /tmp/test-results
 
     steps:
       - checkout
 
-      - run:
-          name: Waiting for Postgres to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 5432 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for Postgress && exit 1
+#       - run:
+#           name: Waiting for Postgres to be ready
+#           command: |
+#             for i in `seq 1 10`;
+#             do
+#               nc -z localhost 5432 && echo Success && exit 0
+#               echo -n .
+#               sleep 1
+#             done
+#             echo Failed waiting for Postgress && exit 1
 
-      - run: mkdir -p $TEST_RESULTS
+#       - run: mkdir -p $TEST_RESULTS
 
-      - run:
-          name: Run unit tests
-          environment:
-            DATABASE_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
-            DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-docker/db/migrations
-          command: |
-            set -ou pipefail
-            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
-            # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
-            # without this option script will return success regardless of testing result due to pipe after test command
-            make test | tee ${TEST_RESULTS}/go-test.out
+#       - run:
+#           name: Run unit tests
+#           environment:
+#             DATABASE_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
+#             DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-docker/db/migrations
+#           command: |
+#             set -ou pipefail
+#             trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
+#             # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
+#             # without this option script will return success regardless of testing result due to pipe after test command
+#             make test | tee ${TEST_RESULTS}/go-test.out
 
 #       - run:
 #           name: Install Docker Compose
@@ -80,9 +80,9 @@ jobs:
 #             docker tag circleci/cci-demo-docker:$TAG jimmydelano/test-repo:$TAG
 #             docker push jimmydelano/test-repo:$TAG
 
-      - store_artifacts:
-          path: /tmp/test-results
-          destination: raw-test-output
+#       - store_artifacts:
+#           path: /tmp/test-results
+#           destination: raw-test-output
 
-      - store_test_results:
-          path: /tmp/test-results
+#       - store_test_results:
+#           path: /tmp/test-results
